apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  namespace: demo
  labels:
    app: replicaset-app
    tier: replicaset-frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
      - name: nginx-redis
        image: nginx:1.29.4
        ports:
        - containerPort: 80
          name: http-port